-- MySQL Script generated by MySQL Workbench
-- Wed Mar 11 16:14:12 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Bank
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Bank
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Bank` DEFAULT CHARACTER SET utf8 ;
USE `Bank` ;

-- -----------------------------------------------------
-- Table `Bank`.`account`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Bank`.`account` ;

CREATE TABLE IF NOT EXISTS `Bank`.`account` (
  `idaccount` INT NOT NULL,
  `account_number` VARCHAR(45) NULL,
  `account_type` VARCHAR(20) NULL,
  `accout_balance` DECIMAL(10,2) NULL,
  `account_limit` DECIMAL(10,2) NULL,
  `account_currency` VARCHAR(20) NULL,
  `account_opened` DATETIME NULL,
  `account_closed` DATETIME NULL,
  `account_status` TINYINT NULL,
  PRIMARY KEY (`idaccount`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Bank`.`account_ownership`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Bank`.`account_ownership` ;

CREATE TABLE IF NOT EXISTS `Bank`.`account_ownership` (
  `idaccount_ownership` INT NOT NULL,
  `customer` INT NULL,
  `account` INT NULL,
  `ownership_type` VARCHAR(10) NULL,
  PRIMARY KEY (`idaccount_ownership`),
  INDEX `ownership_customer_idx` (`customer` ASC) VISIBLE,
  INDEX `ownership_account_idx` (`account` ASC) VISIBLE,
  CONSTRAINT `ownership_customer`
    FOREIGN KEY (`customer`)
    REFERENCES `Bank`.`customer` (`idcustomer`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `ownership_account`
    FOREIGN KEY (`account`)
    REFERENCES `Bank`.`account` (`idaccount`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Bank`.`atm`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Bank`.`atm` ;

CREATE TABLE IF NOT EXISTS `Bank`.`atm` (
  `idatm` INT NOT NULL,
  `atm_location` VARCHAR(45) NULL,
  `atm10` INT NULL,
  `atm20` INT NULL,
  `atm50` INT NULL,
  `atm100` INT NULL,
  `atm200` INT NULL,
  `atm_city` VARCHAR(45) NULL,
  `atm_country` VARCHAR(45) NULL,
  `atm_address1` VARCHAR(45) NULL,
  `atm_address2` VARCHAR(45) NULL,
  `atm_zip` VARCHAR(10) NULL,
  `atm_balance` DECIMAL(10,2) NULL,
  `atm_accountnumber` INT NULL,
  PRIMARY KEY (`idatm`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Bank`.`card`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Bank`.`card` ;

CREATE TABLE IF NOT EXISTS `Bank`.`card` (
  `idcard` INT NOT NULL,
  `card_number` VARCHAR(20) NULL,
  `card_type` VARCHAR(10) NULL,
  `card_type2` VARCHAR(20) NULL,
  `card_type3` VARCHAR(45) NULL,
  `card_pin` VARCHAR(255) NULL,
  `card_status` TINYINT NULL,
  `card_opened` DATETIME NULL,
  `card_closed` DATETIME NULL,
  `card_activated` DATETIME NULL,
  `card_cvv` VARCHAR(255) NULL,
  `card_owner` INT NULL,
  `card_account` INT NULL,
  `cardcol` VARCHAR(45) NULL,
  PRIMARY KEY (`idcard`),
  INDEX `card_owner_idx` (`card_owner` ASC) VISIBLE,
  INDEX `card_account_idx` (`card_account` ASC) VISIBLE,
  CONSTRAINT `card_owner`
    FOREIGN KEY (`card_owner`)
    REFERENCES `Bank`.`customer` (`idcustomer`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `card_account`
    FOREIGN KEY (`card_account`)
    REFERENCES `Bank`.`account` (`idaccount`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Bank`.`customer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Bank`.`customer` ;

CREATE TABLE IF NOT EXISTS `Bank`.`customer` (
  `idcustomer` INT NOT NULL,
  `fname` VARCHAR(20) NULL,
  `lname` VARCHAR(20) NULL,
  `phonenumber` VARCHAR(20) NULL,
  `email` VARCHAR(45) NULL,
  `citizenship1` VARCHAR(20) NULL,
  `citizenship2` VARCHAR(20) NULL,
  `politicalstatus` TINYINT NULL,
  `socialsecnum` VARCHAR(20) NULL,
  `birthdate` DATE NULL,
  `customercreated` DATETIME NULL,
  `customerclosed` DATETIME NULL,
  `customerstatus` TINYINT NULL,
  PRIMARY KEY (`idcustomer`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Bank`.`transaction`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Bank`.`transaction` ;

CREATE TABLE IF NOT EXISTS `Bank`.`transaction` (
  `idtransaction` INT NOT NULL,
  `transaction_date` DATETIME NULL,
  `transaction_atm` INT NULL,
  `transaction_type` VARCHAR(20) NULL,
  `transaction_amount` DECIMAL(10,2) NULL,
  `transaction_currency` VARCHAR(20) NULL,
  `transaction_description` VARCHAR(100) NULL,
  `transaction_status` TINYINT NULL,
  `transaction_source` INT NULL,
  `transaction_target` INT NULL,
  PRIMARY KEY (`idtransaction`),
  INDEX `transaction_atm_idx` (`transaction_atm` ASC) VISIBLE,
  CONSTRAINT `transaction_atm`
    FOREIGN KEY (`transaction_atm`)
    REFERENCES `Bank`.`atm` (`idatm`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Bank`.`transaction_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Bank`.`transaction_type` ;

CREATE TABLE IF NOT EXISTS `Bank`.`transaction_type` (
  `idtransaction_type` INT NOT NULL,
  `account_id` INT NULL,
  `transaction_number` INT NULL,
  `transaction_type` VARCHAR(20) NULL,
  PRIMARY KEY (`idtransaction_type`),
  INDEX `transaction_transactiontype_idx` (`transaction_number` ASC) VISIBLE,
  INDEX `account_transactiontype_idx` (`account_id` ASC) VISIBLE,
  CONSTRAINT `transaction_transactiontype`
    FOREIGN KEY (`transaction_number`)
    REFERENCES `Bank`.`transaction` (`idtransaction`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `account_transactiontype`
    FOREIGN KEY (`account_id`)
    REFERENCES `Bank`.`account` (`idaccount`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
