-- MySQL Script generated by MySQL Workbench
-- Wed Mar 11 14:50:05 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Bank
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Bank
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Bank` DEFAULT CHARACTER SET utf8 ;
USE `Bank` ;

-- -----------------------------------------------------
-- Table `Bank`.`account`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Bank`.`account` ;

CREATE TABLE IF NOT EXISTS `Bank`.`account` (
  `idaccount` INT NOT NULL,
  `account_number` INT NULL,
  `account_type` VARCHAR(20) NULL,
  `account_owner` INT NULL,
  `account_owner2` INT NULL,
  `account_proxy` INT NULL,
  `account_proxy2` INT NULL,
  `accout_balance` DOUBLE NULL,
  `account_limit` DOUBLE NULL,
  `account_currency` VARCHAR(20) NULL,
  `account_opened` DATETIME NULL,
  `account_closed` DATETIME NULL,
  `account_status` TINYINT NULL,
  PRIMARY KEY (`idaccount`),
  INDEX `customer_account_idx` (`account_owner` ASC) VISIBLE,
  INDEX `customer_owner2_idx` (`account_owner2` ASC) VISIBLE,
  INDEX `customer_proxy_idx` (`account_proxy` ASC) VISIBLE,
  INDEX `customer_proxy2_idx` (`account_proxy2` ASC) VISIBLE,
  CONSTRAINT `customer_owner`
    FOREIGN KEY (`account_owner`)
    REFERENCES `Bank`.`customer` (`idcustomer`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `customer_owner2`
    FOREIGN KEY (`account_owner2`)
    REFERENCES `Bank`.`customer` (`idcustomer`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `customer_proxy`
    FOREIGN KEY (`account_proxy`)
    REFERENCES `Bank`.`customer` (`idcustomer`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `customer_proxy2`
    FOREIGN KEY (`account_proxy2`)
    REFERENCES `Bank`.`customer` (`idcustomer`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Bank`.`atm`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Bank`.`atm` ;

CREATE TABLE IF NOT EXISTS `Bank`.`atm` (
  `idatm` INT NOT NULL,
  `atm_location` VARCHAR(45) NULL,
  `atm10` INT NULL,
  `atm20` INT NULL,
  `atm50` INT NULL,
  `atm100` INT NULL,
  `atm200` INT NULL,
  `atm_city` VARCHAR(45) NULL,
  `atm_country` VARCHAR(45) NULL,
  `atm_address1` VARCHAR(45) NULL,
  `atm_address2` VARCHAR(45) NULL,
  `atm_zip` VARCHAR(10) NULL,
  `atm_balance` INT NULL,
  `atm_accountnumber` INT NULL,
  PRIMARY KEY (`idatm`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Bank`.`card`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Bank`.`card` ;

CREATE TABLE IF NOT EXISTS `Bank`.`card` (
  `idcard` INT NOT NULL,
  `card_number` INT NULL,
  `card_type` VARCHAR(10) NULL,
  `card_type2` VARCHAR(20) NULL,
  `card_type3` VARCHAR(45) NULL,
  `card_pin` INT NULL,
  `card_status` TINYINT NULL,
  `card_opened` DATETIME NULL,
  `card_closed` DATETIME NULL,
  `card_activated` DATETIME NULL,
  `card_cvv` INT NULL,
  `card_owner` INT NULL,
  `card_account` INT NULL,
  `cardcol` VARCHAR(45) NULL,
  PRIMARY KEY (`idcard`),
  INDEX `card_owner_idx` (`card_owner` ASC) VISIBLE,
  INDEX `card_account_idx` (`card_account` ASC) VISIBLE,
  CONSTRAINT `card_owner`
    FOREIGN KEY (`card_owner`)
    REFERENCES `Bank`.`customer` (`idcustomer`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `card_account`
    FOREIGN KEY (`card_account`)
    REFERENCES `Bank`.`account` (`idaccount`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Bank`.`customer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Bank`.`customer` ;

CREATE TABLE IF NOT EXISTS `Bank`.`customer` (
  `idcustomer` INT NOT NULL,
  `fname` VARCHAR(20) NULL,
  `lname` VARCHAR(20) NULL,
  `phonenumber` VARCHAR(20) NULL,
  `email` VARCHAR(45) NULL,
  `citizenship1` VARCHAR(20) NULL,
  `citizenship2` VARCHAR(20) NULL,
  `politicalstatus` TINYINT NULL,
  `socialsecnum` VARCHAR(20) NULL,
  `birthdate` DATE NULL,
  `customercreated` DATETIME NULL,
  `customerclosed` DATETIME NULL,
  `customerstatus` TINYINT NULL,
  PRIMARY KEY (`idcustomer`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Bank`.`transaction`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Bank`.`transaction` ;

CREATE TABLE IF NOT EXISTS `Bank`.`transaction` (
  `idtransaction` INT NOT NULL,
  `transaction_date` DATETIME NULL,
  `transaction_atm` INT NULL,
  `transaction_type` VARCHAR(20) NULL,
  `transaction_amount` DOUBLE NULL,
  `transaction_currency` VARCHAR(20) NULL,
  `transaction_description` VARCHAR(100) NULL,
  `transaction_status` TINYINT NULL,
  `transaction_source` INT NULL,
  `transaction_target` INT NULL,
  PRIMARY KEY (`idtransaction`),
  INDEX `transaction_source_idx` (`transaction_source` ASC) VISIBLE,
  INDEX `transaction_target_idx` (`transaction_target` ASC) VISIBLE,
  INDEX `transaction_atm_idx` (`transaction_atm` ASC) VISIBLE,
  CONSTRAINT `transaction_source`
    FOREIGN KEY (`transaction_source`)
    REFERENCES `Bank`.`account` (`idaccount`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `transaction_target`
    FOREIGN KEY (`transaction_target`)
    REFERENCES `Bank`.`account` (`idaccount`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `transaction_atm`
    FOREIGN KEY (`transaction_atm`)
    REFERENCES `Bank`.`atm` (`idatm`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
