-- MySQL Script generated by MySQL Workbench
-- Mon Apr 20 14:25:12 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema bank_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bank_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bank_db` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `bank_db` ;

-- -----------------------------------------------------
-- Table `bank_db`.`customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bank_db`.`customer` (
  `idcustomer` INT NOT NULL AUTO_INCREMENT,
  `fname` VARCHAR(20) NULL DEFAULT NULL,
  `lname` VARCHAR(20) NULL DEFAULT NULL,
  `phonenumber` VARCHAR(20) NULL DEFAULT NULL,
  `email` VARCHAR(45) NULL DEFAULT NULL,
  `citizenship1` VARCHAR(20) NULL DEFAULT NULL,
  `citizenship2` VARCHAR(20) NULL DEFAULT NULL,
  `politicalstatus` TINYINT NULL DEFAULT NULL,
  `socialsecnum` VARCHAR(20) NULL DEFAULT NULL,
  `birthdate` DATE NULL DEFAULT NULL,
  `customercreated` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `customerclosed` DATETIME NULL DEFAULT NULL,
  `customerstatus` TINYINT NULL DEFAULT '1',
  PRIMARY KEY (`idcustomer`))
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `bank_db`.`account`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bank_db`.`account` (
  `idaccount` INT NOT NULL AUTO_INCREMENT,
  `account_number` VARCHAR(45) NULL DEFAULT NULL,
  `account_type` VARCHAR(20) NULL DEFAULT NULL,
  `account_balance` DECIMAL(10,2) NULL DEFAULT NULL,
  `account_limit` DECIMAL(10,2) NULL DEFAULT NULL,
  `account_currency` VARCHAR(20) NULL DEFAULT NULL,
  `account_opened` DATETIME NULL DEFAULT NULL,
  `account_closed` DATETIME NULL DEFAULT NULL,
  `account_status` TINYINT NULL DEFAULT NULL,
  `account_customerid` INT NULL DEFAULT NULL,
  PRIMARY KEY (`idaccount`),
  INDEX `account_customer_idx` (`account_customerid` ASC) VISIBLE,
  CONSTRAINT `account_customer`
    FOREIGN KEY (`account_customerid`)
    REFERENCES `bank_db`.`customer` (`idcustomer`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 15
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `bank_db`.`card`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bank_db`.`card` (
  `idcard` INT NOT NULL AUTO_INCREMENT,
  `card_number` VARCHAR(20) NULL DEFAULT NULL,
  `card_type` VARCHAR(10) NULL DEFAULT NULL,
  `card_type2` VARCHAR(20) NULL DEFAULT NULL,
  `card_type3` VARCHAR(45) NULL DEFAULT NULL,
  `card_pin` VARCHAR(255) NULL DEFAULT NULL,
  `card_status` TINYINT NULL DEFAULT NULL,
  `card_opened` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `card_closed` DATETIME NULL DEFAULT NULL,
  `card_activated` DATETIME NULL DEFAULT NULL,
  `card_cvv` VARCHAR(255) NULL DEFAULT NULL,
  `card_owner` INT NULL DEFAULT NULL,
  `card_account` INT NULL DEFAULT NULL,
  `cardcol` VARCHAR(45) NULL DEFAULT NULL,
  `pin_attempts` INT NULL DEFAULT '0',
  PRIMARY KEY (`idcard`),
  INDEX `card_owner_idx` (`card_owner` ASC) VISIBLE,
  CONSTRAINT `card_owner`
    FOREIGN KEY (`card_owner`)
    REFERENCES `bank_db`.`customer` (`idcustomer`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 15
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `bank_db`.`accouts_to_cards`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bank_db`.`accouts_to_cards` (
  `idaccouts_to_cards` INT NOT NULL,
  `atc_account` INT NULL DEFAULT NULL,
  `atc_card` INT NULL DEFAULT NULL,
  PRIMARY KEY (`idaccouts_to_cards`),
  INDEX `atc_card_idx` (`atc_card` ASC) VISIBLE,
  INDEX `atc_account_idx` (`atc_account` ASC) VISIBLE,
  CONSTRAINT `atc_account`
    FOREIGN KEY (`atc_account`)
    REFERENCES `bank_db`.`account` (`idaccount`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `atc_card`
    FOREIGN KEY (`atc_card`)
    REFERENCES `bank_db`.`card` (`idcard`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `bank_db`.`atm`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bank_db`.`atm` (
  `idatm` INT NOT NULL AUTO_INCREMENT,
  `atm_location` VARCHAR(45) NULL DEFAULT NULL,
  `atm10` INT NULL DEFAULT '0',
  `atm20` INT NULL DEFAULT '0',
  `atm50` INT NULL DEFAULT '0',
  `atm100` INT NULL DEFAULT '0',
  `atm200` INT NULL DEFAULT '0',
  `atm_city` VARCHAR(45) NULL DEFAULT NULL,
  `atm_country` VARCHAR(45) NULL DEFAULT NULL,
  `atm_address1` VARCHAR(45) NULL DEFAULT NULL,
  `atm_address2` VARCHAR(45) NULL DEFAULT NULL,
  `atm_zip` VARCHAR(10) NULL DEFAULT NULL,
  `atm_balance` DECIMAL(10,2) NULL DEFAULT NULL,
  `atm_accountnumber` INT NULL DEFAULT NULL,
  PRIMARY KEY (`idatm`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bank_db`.`transaction`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bank_db`.`transaction` (
  `idtransaction` INT NOT NULL AUTO_INCREMENT,
  `transaction_date` DATETIME NULL DEFAULT NULL,
  `transaction_atm` INT NULL DEFAULT NULL,
  `transaction_type` VARCHAR(20) NULL DEFAULT NULL,
  `transaction_amount` DECIMAL(10,2) NULL DEFAULT NULL,
  `transaction_currency` VARCHAR(20) NULL DEFAULT NULL,
  `transaction_description` VARCHAR(100) NULL DEFAULT NULL,
  `transaction_status` TINYINT NULL DEFAULT NULL,
  `transaction_source` INT NULL DEFAULT NULL,
  `transaction_target` INT NULL DEFAULT NULL,
  PRIMARY KEY (`idtransaction`),
  INDEX `transaction_atm_idx` (`transaction_atm` ASC) VISIBLE,
  CONSTRAINT `transaction_atm`
    FOREIGN KEY (`transaction_atm`)
    REFERENCES `bank_db`.`atm` (`idatm`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 153
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `bank_db`.`transaction_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bank_db`.`transaction_type` (
  `idtransaction_type` INT NOT NULL,
  `account_id` INT NULL DEFAULT NULL,
  `transaction_number` INT NULL DEFAULT NULL,
  `transaction_type` VARCHAR(20) NULL DEFAULT NULL,
  PRIMARY KEY (`idtransaction_type`),
  INDEX `transaction_transactiontype_idx` (`transaction_number` ASC) VISIBLE,
  INDEX `account_transactiontype_idx` (`account_id` ASC) VISIBLE,
  CONSTRAINT `account_transactiontype`
    FOREIGN KEY (`account_id`)
    REFERENCES `bank_db`.`account` (`idaccount`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `transaction_transactiontype`
    FOREIGN KEY (`transaction_number`)
    REFERENCES `bank_db`.`transaction` (`idtransaction`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;

USE `bank_db` ;

-- -----------------------------------------------------
-- procedure credit_withdrawal
-- -----------------------------------------------------

DELIMITER $$
USE `bank_db`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `credit_withdrawal`(
    IN account_id INT, 
    IN amount_to_withdraw DECIMAL(10,2),
    IN description_text VARCHAR(255) -- 1. LISÄTTY TÄMÄ PARAMETRI
)
BEGIN
    DECLARE rows_affected INT DEFAULT 0;

    -- Virheenhallinta
    DECLARE EXIT HANDLER FOR SQLEXCEPTION
    BEGIN
        GET DIAGNOSTICS CONDITION 1 @p1 = RETURNED_SQLSTATE, @p2 = MESSAGE_TEXT;
        ROLLBACK;
        SELECT CONCAT('Error: ', @p1, ' ', @p2) AS result;
    END;

    START TRANSACTION;

    -- Päivitetään saldo
    UPDATE account 
    SET account_balance = account_balance - amount_to_withdraw 
    WHERE idaccount = account_id 
    AND (account_balance + account_limit) >= amount_to_withdraw;

    SET rows_affected = ROW_COUNT();

    IF rows_affected > 0 THEN
        -- 2. PÄIVITETTY INSERT: Lisätty transaction_description
        INSERT INTO transaction (
            transaction_amount, 
            transaction_date, 
            transaction_status, 
            transaction_source, 
            transaction_description -- Varmista että tämä sarakkeen nimi on oikein taulussasi!
        ) 
        VALUES (
            -amount_to_withdraw, 
            NOW(), 
            1, 
            account_id, 
            description_text -- Tallennetaan annettu kuvaus
        );
        
        COMMIT;
        SELECT 'Success' AS result;
    ELSE
        ROLLBACK;
        SELECT 'Credit limit exceeded' AS result;
    END IF;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure transfer_money
-- -----------------------------------------------------

DELIMITER $$
USE `bank_db`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `transfer_money`(
    IN source_id INT, 
    IN target_id INT, 
    IN amount_to_transfer DECIMAL(10,2),
    IN description_text VARCHAR(255)
)
BEGIN
    DECLARE rows_affected INT DEFAULT 0;

    DECLARE EXIT HANDLER FOR SQLEXCEPTION
    BEGIN
        ROLLBACK;
        SELECT 'Error: Database error' AS result;
    END;

    START TRANSACTION;

    -- 1. Vähennetään rahat lähettäjältä (tarkistetaan että saldo + luottoraja riittää)
    UPDATE account 
    SET account_balance = account_balance - amount_to_transfer 
    WHERE idaccount = source_id 
    AND (account_balance + account_limit) >= amount_to_transfer;

    SET rows_affected = ROW_COUNT();

    IF rows_affected > 0 THEN
        -- 2. Lisätään rahat vastaanottajalle
        UPDATE account 
        SET account_balance = account_balance + amount_to_transfer 
        WHERE idaccount = target_id;

        IF ROW_COUNT() > 0 THEN
            -- 3. Lisätään tapahtumamerkintä lähettäjälle
            INSERT INTO transaction (transaction_amount, transaction_date, transaction_status, transaction_source, transaction_description) 
            VALUES (-amount_to_transfer, NOW(), 1, source_id, CONCAT('Siirto: ', description_text));
            
            -- 4. Lisätään tapahtumamerkintä vastaanottajalle
            INSERT INTO transaction (transaction_amount, transaction_date, transaction_status, transaction_source, transaction_description) 
            VALUES (amount_to_transfer, NOW(), 1, target_id, CONCAT('Saapunut: ', description_text));

            COMMIT;
            SELECT 'Success' AS result;
        ELSE
            -- Jos vastaanottajaa ei löytynyt, perutaan kaikki
            ROLLBACK;
            SELECT 'Target account not found' AS result;
        END IF;
    ELSE
        ROLLBACK;
        SELECT 'Insufficient funds or credit limit exceeded' AS result;
    END IF;
END$$

DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
